apiVersion: v1alpha1
kind: KubeAuthenticationConfig
configuration:
  anonymous:
    conditions:
    - path: /livez
    - path: /readyz
    - path: /healthz
    enabled: true
  jwt:
  - issuer:
      url: "https://keycloak.external.homelab.aliktb.com/realms/homelab"
      audiences:
      - kubernetes-homelab-dev
    claimMappings:
      username:
        claim: preferred_username
        prefix: "oidc:"
      groups:
        claim: groups
        prefix: "oidc:"
